# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a67cf0bbd7244a7efbbd0b0f8ba2824094264ca485778411f665fa3a2c95e692b33e2f7d816dbea87d1a9e1c870f56519026e259a78cc02cc6882aaf1115277b
  admin_secret: lolcontrol

test:
  secret_key_base: 8d4402d4150fde95b56fcbee00b8c9e4587906760cedaeca3bc93c24dc9c438058d12c1ad47dcc58aac5d156883742acbe567653f44a5d58a0198fd7fc6995a9
  admin_secret: lolcontrol

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
